version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - PORT=3000
      - REDIRECT_URL=http://localhost:3000/login
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    command: go run main.go
